/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.roncoder.gesuniversity.frames;

import com.roncoder.gesuniversity.models.ges2.Matiere;
import javax.swing.JOptionPane;

/**
 *
 * @author ronal
 */
public class MatiereDialog extends javax.swing.JDialog {

    private Dashboard dashboard;
    private Matiere matiere;

    /**
     * Creates new form MatiereDialog
     *
     * @param dashboard
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public MatiereDialog(Dashboard dashboard) {
        super(dashboard, true);
        this.dashboard = dashboard;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * Creates new form SalleDialog
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public MatiereDialog() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * Creates new form SalleDialog
     *
     * @param matiere
     * @param dashboard
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public MatiereDialog(Matiere matiere, Dashboard dashboard) {
        super(dashboard, true);
        this.dashboard = dashboard;
        initComponents();
        setLocationRelativeTo(null);
        this.matiere = matiere;
        this.btn_cancel.setEnabled(false);
        this.code.setEnabled(false);
        setDefaultSalle();
    }

    private void setDefaultSalle() {
        this.code.setText(matiere.getCode());
        this.libelle.setText(matiere.getLibelle());
        this.vol_h_cm.setText(matiere.getVol_cm().split(" ")[0]);
        this.vol_h_td.setText(matiere.getVol_td().split(" ")[0]);
        this.vol_h_tp.setText(matiere.getVol_tp().split(" ")[0]);
        this.nb_credit.setText(String.valueOf(matiere.getNb_credit()));
        this.category.setSelectedItem(matiere.getCategory());
    }

    public void initViews() {
        this.code.setText("");
        this.libelle.setText("");
        this.vol_h_cm.setText("");
        this.vol_h_td.setText("");
        this.vol_h_tp.setText("");
        this.nb_credit.setText("");
        this.category.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        app_options = new javax.swing.JPanel();
        app_description = new javax.swing.JLabel();
        close_btn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        code = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        libelle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vol_h_td = new javax.swing.JFormattedTextField();
        vol_h_tp = new javax.swing.JFormattedTextField();
        nb_credit = new javax.swing.JFormattedTextField();
        vol_h_cm = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(400, 400));
        setUndecorated(true);

        app_options.setBackground(new java.awt.Color(224, 224, 224));
        app_options.setMaximumSize(new java.awt.Dimension(300, 32));
        app_options.setMinimumSize(new java.awt.Dimension(300, 32));

        app_description.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        app_description.setForeground(new java.awt.Color(51, 51, 51));
        app_description.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        app_description.setText("Ajout d'une nouvelle UE");

        close_btn.setBackground(new java.awt.Color(255, 0, 0));
        close_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronal\\Documents\\NetBeansProjects\\gesUniversity\\src\\main\\java\\com\\roncoder\\gesuniversity\\frames\\images\\cancel.png")); // NOI18N
        close_btn.setToolTipText("Fermer");
        close_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_btnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout app_optionsLayout = new javax.swing.GroupLayout(app_options);
        app_options.setLayout(app_optionsLayout);
        app_optionsLayout.setHorizontalGroup(
            app_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_optionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(app_description, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        app_optionsLayout.setVerticalGroup(
            app_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_optionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(app_description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(close_btn, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel1.setBackground(new java.awt.Color(29, 53, 87));
        jPanel1.setMaximumSize(new java.awt.Dimension(300, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 100));
        jPanel1.setLayout(null);

        code.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });
        jPanel1.add(code);
        code.setBounds(174, 22, 186, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Code : ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 28, 116, 20);

        btn_submit.setBackground(new java.awt.Color(69, 123, 157));
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setText("Enregistrer");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit);
        btn_submit.setBounds(270, 314, 90, 30);

        btn_cancel.setBackground(new java.awt.Color(255, 55, 22));
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("Annuler");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel);
        btn_cancel.setBounds(40, 314, 70, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Libelle : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 72, 116, 20);
        jPanel1.add(libelle);
        libelle.setBounds(174, 66, 186, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre crédit : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 114, 116, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vol. Horaire CM : ");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 156, 116, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Vol. Horaire TD : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 198, 116, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Vol. Horaire TP : ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 238, 116, 20);

        vol_h_td.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel1.add(vol_h_td);
        vol_h_td.setBounds(174, 190, 91, 30);

        vol_h_tp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel1.add(vol_h_tp);
        vol_h_tp.setBounds(174, 230, 91, 30);

        nb_credit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel1.add(nb_credit);
        nb_credit.setBounds(174, 106, 186, 30);

        vol_h_cm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel1.add(vol_h_cm);
        vol_h_cm.setBounds(174, 148, 91, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Heure(s)");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(277, 156, 80, 20);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Heure(s)");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(277, 198, 80, 20);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Heure(s)");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(277, 238, 80, 20);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Catégorie : ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 279, 116, 20);

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fondamentalle", "Optionnelle", "Complementaire" }));
        jPanel1.add(category);
        category.setBounds(174, 274, 186, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(app_options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(app_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_close_btnMouseClicked

    private void close_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseEntered
        close_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronal\\Documents\\NetBeansProjects\\gesUniversity\\src\\main\\java\\com\\roncoder\\gesuniversity\\frames\\images\\cancel_hover.png")); // NOI18N
    }//GEN-LAST:event_close_btnMouseEntered

    private void close_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseExited
        close_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronal\\Documents\\NetBeansProjects\\gesUniversity\\src\\main\\java\\com\\roncoder\\gesuniversity\\frames\\images\\cancel.png")); // NOI18N
    }//GEN-LAST:event_close_btnMouseExited

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // Save element to the database. and notify the table.
        String code_str = this.code.getText();
        String libelle_str = this.libelle.getText();
        String vol_cm_str = this.vol_h_cm.getText() + " H";
        String vol_td_str = this.vol_h_td.getText() + " H";
        String vol_tp_str = this.vol_h_tp.getText() + " H";
        String category_str = (String) this.category.getSelectedItem();
        int nb_credit_str = 0;
        try {
            nb_credit_str = Integer.parseInt(this.nb_credit.getText());
        } catch (java.lang.NumberFormatException ex) {
        } finally {
            // Validation.
            if (requiredFields()) {
                if (matiere == null) {
                    dashboard.addMatiere(new Matiere(code_str, libelle_str, nb_credit_str,
                            vol_cm_str, vol_td_str, vol_tp_str, category_str));
                } else {
                    if (requiredFieldsNotOld()) {
                        matiere.setLibelle(libelle_str);
                        matiere.setNb_credit(nb_credit_str);
                        matiere.setVol_cm(vol_cm_str);
                        matiere.setVol_td(vol_td_str);
                        matiere.setVol_tp(vol_tp_str);
                        matiere.setCategory(category_str);
                        dashboard.updateMatiere(matiere);
                    }
                }
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private boolean requiredFieldsNotOld() {
        // Check if the fields are different.
        if (code.getText().trim().equals(matiere.getCode())
                && libelle.getText().trim().equals(matiere.getLibelle())
                && category.getSelectedItem().equals(matiere.getCategory())
                && nb_credit.getText().trim().equals(String.valueOf(matiere.getNb_credit()))
                && matiere.getVol_cm().equals(vol_h_cm.getText().trim() + " H")
                && matiere.getVol_td().equals(vol_h_td.getText().trim() + " H")
                && matiere.getVol_tp().equals(vol_h_tp.getText().trim() + " H")) {
            JOptionPane.showMessageDialog(null, "Aucune modification apportée.");
            return false;
        }
        return true;
    }

    private boolean requiredFields() {
        if (code.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez indiquer le code de la matière.");
            return false;
        }
        if (libelle.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez indiquer le libelle de la matière.");
            return false;
        }
        if (nb_credit.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez indiquer le nombre de crédit de la matière.");
            return false;
        }
        if (vol_h_cm.getText().trim().equals("")
                || vol_h_tp.getText().trim().equals("")
                || vol_h_td.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez indiquer le volume horaire de la matière.");
            return false;
        }
        return true;
    }

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        initViews();
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatiereDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MatiereDialog().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel app_description;
    private javax.swing.JPanel app_options;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JLabel close_btn;
    private javax.swing.JTextField code;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField libelle;
    private javax.swing.JFormattedTextField nb_credit;
    private javax.swing.JFormattedTextField vol_h_cm;
    private javax.swing.JFormattedTextField vol_h_td;
    private javax.swing.JFormattedTextField vol_h_tp;
    // End of variables declaration//GEN-END:variables
}
