/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.roncoder.gesuniversity.frames;

import com.roncoder.gesuniversity.models.ges1.Salle;
import javax.swing.JOptionPane;

/**
 *
 * @author ronal
 */
public class SalleDialog extends javax.swing.JDialog {

    private Dashboard dashboard;
    private Salle salle;

    /**
     * Creates new form SalleDialog
     *
     * @param dashboard
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public SalleDialog(Dashboard dashboard) {
        super(dashboard, true);
        initComponents();
        setLocationRelativeTo(null);
        this.dashboard = dashboard;
    }

    /**
     * Creates new form SalleDialog
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public SalleDialog() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * Creates new form SalleDialog
     *
     * @param salle
     * @param dashboard
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public SalleDialog(Salle salle, Dashboard dashboard) {
        super(dashboard, true);
        initComponents();
        setLocationRelativeTo(null);
        this.salle = salle;
        this.dashboard = dashboard;
        this.btn_cancel.setEnabled(false);
        this.code.setEnabled(false);
        setDefaultSalle();
    }

    private void setDefaultSalle() {
        this.code.setText(salle.getCode());
        this.libelle.setText(salle.getLibelle());
        this.capacity.setText(String.valueOf(salle.getCapacity()));
        this.num_campus.setText(String.valueOf(salle.getNum_campue()));
        this.localisation.setText(salle.getLocalisation());
    }

    private void initViews() {
        this.code.setText("");
        this.libelle.setText("");
        this.capacity.setText("");
        this.num_campus.setText("");
        this.localisation.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        app_options = new javax.swing.JPanel();
        app_description = new javax.swing.JLabel();
        close_btn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        code = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        libelle = new javax.swing.JTextField();
        capacity = new javax.swing.JTextField();
        num_campus = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        localisation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(400, 400));
        setUndecorated(true);
        setResizable(false);

        app_options.setBackground(new java.awt.Color(224, 224, 224));
        app_options.setMaximumSize(new java.awt.Dimension(300, 32));
        app_options.setMinimumSize(new java.awt.Dimension(300, 32));
        app_options.setPreferredSize(new java.awt.Dimension(300, 32));

        app_description.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        app_description.setForeground(new java.awt.Color(51, 51, 51));
        app_description.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        app_description.setText("Ajout d'une nouvelle salle");

        close_btn.setBackground(new java.awt.Color(255, 0, 0));
        close_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronal\\Documents\\NetBeansProjects\\gesUniversity\\src\\main\\java\\com\\roncoder\\gesuniversity\\frames\\images\\cancel.png")); // NOI18N
        close_btn.setToolTipText("Fermer");
        close_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_btnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout app_optionsLayout = new javax.swing.GroupLayout(app_options);
        app_options.setLayout(app_optionsLayout);
        app_optionsLayout.setHorizontalGroup(
            app_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_optionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(app_description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        app_optionsLayout.setVerticalGroup(
            app_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_optionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(app_description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(close_btn, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel1.setBackground(new java.awt.Color(29, 53, 87));
        jPanel1.setMaximumSize(new java.awt.Dimension(300, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 100));
        jPanel1.setLayout(null);

        code.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });
        jPanel1.add(code);
        code.setBounds(190, 32, 170, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Libelle : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 90, 120, 20);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Code : ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 40, 120, 20);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Capacité : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 150, 120, 20);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Numéro campus : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 210, 120, 20);

        libelle.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(libelle);
        libelle.setBounds(190, 84, 170, 30);

        capacity.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(capacity);
        capacity.setBounds(190, 142, 170, 30);

        num_campus.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(num_campus);
        num_campus.setBounds(190, 200, 170, 30);

        btn_submit.setBackground(new java.awt.Color(69, 123, 157));
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setText("Enregistrer");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit);
        btn_submit.setBounds(270, 310, 90, 30);

        btn_cancel.setBackground(new java.awt.Color(255, 55, 22));
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("Annuler");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel);
        btn_cancel.setBounds(50, 310, 70, 30);

        localisation.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(localisation);
        localisation.setBounds(190, 258, 170, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Localisation : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 270, 120, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(app_options, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(app_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_close_btnMouseClicked

    private void close_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseEntered
        close_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronal\\Documents\\NetBeansProjects\\gesUniversity\\src\\main\\java\\com\\roncoder\\gesuniversity\\frames\\images\\cancel_hover.png")); // NOI18N
    }//GEN-LAST:event_close_btnMouseEntered

    private void close_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseExited
        close_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronal\\Documents\\NetBeansProjects\\gesUniversity\\src\\main\\java\\com\\roncoder\\gesuniversity\\frames\\images\\cancel.png")); // NOI18N
    }//GEN-LAST:event_close_btnMouseExited

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        initViews();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // Save element to the database. and notify the table.
        String code_str = this.code.getText();
        String libelle_str = this.libelle.getText();
        String localisation_str = this.localisation.getText();
        int num_campus_str = 0, capacity_str = 0;
        try {
            num_campus_str = Integer.parseInt(this.num_campus.getText());
            capacity_str = Integer.parseInt(this.capacity.getText());
        } catch (java.lang.NumberFormatException ex) {
        } finally {
            // Validation.
            if (requiredFields()) {
                if (salle == null) {
                    dashboard.addSalle(new Salle(code_str, libelle_str, localisation_str,
                            num_campus_str, capacity_str));
                } else {
                    if (requiredFieldsNotOld()) {
                        salle.setLibelle(libelle_str);
                        salle.setCapacity(capacity_str);
                        salle.setLocalisation(localisation_str);
                        salle.setNum_campue(num_campus_str);
                        dashboard.updateSalle(salle);
                    }
                }
                this.setVisible(false);
            }
        }

    }//GEN-LAST:event_btn_submitActionPerformed

    private boolean requiredFieldsNotOld() {
        // Check if the fields are different.
        if (code.getText().trim().equals(salle.getCode())
                && libelle.getText().trim().equals(salle.getLibelle())
                && localisation.getText().trim().equals(salle.getLocalisation())
                && capacity.getText().trim().equals(String.valueOf(salle.getCapacity()))
                && num_campus.getText().trim().equals(String.valueOf(salle.getNum_campue()))) {
            JOptionPane.showMessageDialog(null, "Aucune modification apportée.");
            return false;
        }
        return true;
    }

    private boolean requiredFields() {
        if (code.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez indiquer le code de la salle.");
            return false;
        }
        if (libelle.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez indiquer le libelle de la salle.");
            return false;
        }
        if (localisation.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez indiquer la localisation de la salle.");
            return false;
        }
        if (num_campus.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez indiquer le numero de campus la salle.");
            return false;
        }
        if (capacity.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez indiquer la capacité de la salle.");
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalleDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SalleDialog().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel app_description;
    private javax.swing.JPanel app_options;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_submit;
    private javax.swing.JTextField capacity;
    private javax.swing.JLabel close_btn;
    private javax.swing.JTextField code;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField libelle;
    private javax.swing.JTextField localisation;
    private javax.swing.JTextField num_campus;
    // End of variables declaration//GEN-END:variables
}
