/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.roncoder.gesuniversity.frames;

import com.roncoder.gesuniversity.db.DBManager;
import com.roncoder.gesuniversity.models.ges3.UE;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ronal
 */
public class UEFrame extends javax.swing.JDialog {

    private final Dashboard dashboard;
    private UE ue;

    /**
     * Creates new form addMatiere
     *
     * @param frame
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public UEFrame(javax.swing.JFrame frame) {
        super(frame, true);
        initComponents();
        this.dashboard = (Dashboard) frame;
        setFiliereComboBox();
        this.setLocationRelativeTo(null);
    }

    /**
     * Creates new form SalleDialog
     *
     * @param ue
     * @param dashboard
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public UEFrame(UE ue, Dashboard dashboard) {
        super(dashboard, true);
        this.dashboard = dashboard;
        initComponents();
        setFiliereComboBox();
        setLocationRelativeTo(null);
        this.ue = ue;
        this.btn_cancel.setEnabled(false);
        this.code.setEnabled(false);
        setDefaultSalle();
    }

    private void setDefaultSalle() {
        this.code.setText(ue.getCode());
        this.libelle.setText(ue.getLibelle());
        this.vol_cm.setText(String.valueOf(ue.getVol_cm()));
        this.vol_td.setText(String.valueOf(ue.getVol_td()));
        this.vol_tp.setText(String.valueOf(ue.getVol_tp()));
        this.nb_credit.setText(String.valueOf(ue.getNb_credit()));
        this.category.setSelectedItem(ue.getCategory());
        this.filiere.setSelectedItem(ue.getFiliere_code());
    }

    private void setFiliereComboBox() {
        DBManager db = new DBManager();
        try {
            List<String> fac = new ArrayList<>();
            db.select("filieres", new String[]{"*"});
            ResultSet result = db.get();
            while (result.next()) {
                fac.add(result.getString("code"));
            }
            filiere.setModel(new javax.swing.DefaultComboBoxModel<>(fac.toArray(new String[]{})));
            filiere.setSelectedIndex(0);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void initViews() {
        this.code.setText("");
        this.libelle.setText("");
        this.nb_credit.setText("");
        this.vol_cm.setText("");
        this.vol_td.setText("");
        this.vol_tp.setText("");
        this.category.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        app_options = new javax.swing.JPanel();
        app_description = new javax.swing.JLabel();
        close_btn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nb_credit = new javax.swing.JFormattedTextField();
        libelle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        filiere = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        vol_cm = new javax.swing.JFormattedTextField();
        vol_td = new javax.swing.JFormattedTextField();
        vol_tp = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(500, 450));
        setMinimumSize(new java.awt.Dimension(500, 450));
        setModal(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 450));

        app_options.setBackground(new java.awt.Color(224, 224, 224));
        app_options.setMaximumSize(new java.awt.Dimension(300, 32));
        app_options.setMinimumSize(new java.awt.Dimension(300, 32));

        app_description.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        app_description.setForeground(new java.awt.Color(51, 51, 51));
        app_description.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        app_description.setText("Ajout d'une nouvelle matière");

        close_btn.setBackground(new java.awt.Color(255, 0, 0));
        close_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronal\\Documents\\NetBeansProjects\\gesUniversity\\src\\main\\java\\com\\roncoder\\gesuniversity\\frames\\images\\cancel.png")); // NOI18N
        close_btn.setToolTipText("Fermer");
        close_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_btnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout app_optionsLayout = new javax.swing.GroupLayout(app_options);
        app_options.setLayout(app_optionsLayout);
        app_optionsLayout.setHorizontalGroup(
            app_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_optionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(app_description, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        app_optionsLayout.setVerticalGroup(
            app_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_optionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(app_description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(close_btn, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel1.setBackground(new java.awt.Color(29, 53, 87));
        jPanel1.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Code : ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 40, 60, 20);
        jPanel1.add(code);
        code.setBounds(120, 30, 130, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Libelle : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 90, 60, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nbre crédit : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 40, 80, 20);

        nb_credit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        jPanel1.add(nb_credit);
        nb_credit.setBounds(370, 30, 90, 30);
        jPanel1.add(libelle);
        libelle.setBounds(120, 80, 340, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Filière : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 140, 60, 20);

        filiere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(filiere);
        filiere.setBounds(120, 130, 210, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Categorie : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 190, 70, 20);

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fondamentalle", "Complementaire", "Optionnelle" }));
        jPanel1.add(category);
        category.setBounds(120, 180, 210, 30);

        jPanel2.setBackground(new java.awt.Color(29, 53, 87));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Volume horaires ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cours Magistraux : ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(11, 24, 105, 16);
        jPanel2.add(vol_cm);
        vol_cm.setBounds(11, 46, 105, 30);
        jPanel2.add(vol_td);
        vol_td.setBounds(134, 46, 166, 30);
        jPanel2.add(vol_tp);
        vol_tp.setBounds(318, 46, 111, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Travails Dirigé (TD)  : ");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(134, 24, 166, 16);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Travails Pratiques  : ");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(318, 24, 111, 16);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 230, 440, 100);

        btn_cancel.setBackground(new java.awt.Color(255, 55, 22));
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("Annuler");
        jPanel1.add(btn_cancel);
        btn_cancel.setBounds(30, 364, 100, 30);

        btn_submit.setBackground(new java.awt.Color(69, 123, 157));
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setText("Enregistrer");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit);
        btn_submit.setBounds(367, 364, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(app_options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(app_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_close_btnMouseClicked

    private void close_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseEntered
        close_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronal\\Documents\\NetBeansProjects\\gesUniversity\\src\\main\\java\\com\\roncoder\\gesuniversity\\frames\\images\\cancel_hover.png")); // NOI18N
    }//GEN-LAST:event_close_btnMouseEntered

    private void close_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseExited
        close_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ronal\\Documents\\NetBeansProjects\\gesUniversity\\src\\main\\java\\com\\roncoder\\gesuniversity\\frames\\images\\cancel.png")); // NOI18N
    }//GEN-LAST:event_close_btnMouseExited

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // Save element to the database. and notify the table.
        String code_str = this.code.getText();
        String libelle_str = this.libelle.getText();
        String filiere_str = (String) this.filiere.getSelectedItem();
        String category_str = (String) this.category.getSelectedItem();
        int nb_credit_str = 0, vol_cm_str = 0, vol_td_str = 0, vol_tp_str = 0;
        try {
            nb_credit_str = Integer.parseInt(this.nb_credit.getText());
            vol_cm_str = Integer.parseInt(this.vol_cm.getText());
            vol_td_str = Integer.parseInt(this.vol_td.getText());
            vol_tp_str = Integer.parseInt(this.vol_tp.getText());
        } catch (java.lang.NumberFormatException ex) {
        } finally {
            // Validation.
            if (requiredFields()) {
                if (ue == null) {
                    dashboard.addUE(new UE(code_str, filiere_str, libelle_str, nb_credit_str,
                            vol_cm_str, vol_td_str, vol_tp_str, category_str));
                } else {
                    if (requiredFieldsNotOld()) {
                        ue.setLibelle(libelle_str);
                        ue.setNb_credit(nb_credit_str);
                        ue.setVol_cm(vol_cm_str);
                        ue.setVol_td(vol_td_str);
                        ue.setVol_tp(vol_tp_str);
                        ue.setCategory(category_str);
                        dashboard.updateUE(ue);
                    }
                }
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private boolean requiredFields() {
        if (code.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez indiquer le code de la matière.");
            return false;
        }
        if (libelle.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez indiquer le libelle de la matière.");
            return false;
        }
        if (nb_credit.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez indiquer le nombre de crédit de la matière.");
            return false;
        }
        if (vol_cm.getText().trim().equals("")
                || vol_tp.getText().trim().equals("")
                || vol_td.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez indiquer le volume horaire de la matière.");
            return false;
        }
        return true;
    }

    private boolean requiredFieldsNotOld() {
        // Check if the fields are different.
        if (code.getText().trim().equals(ue.getCode())
                && libelle.getText().trim().equals(ue.getLibelle())
                && filiere.getSelectedItem().equals(ue.getFiliere())
                && category.getSelectedItem().equals(ue.getCategory())
                && nb_credit.getText().trim().equals(String.valueOf(ue.getNb_credit()))
                && vol_cm.getText().trim().equals(String.valueOf(ue.getVol_cm()))
                && vol_td.getText().trim().equals(String.valueOf(ue.getVol_td()))
                && vol_tp.getText().trim().equals(String.valueOf(ue.getVol_tp()))) {
            JOptionPane.showMessageDialog(null, "Aucune modification apportée.");
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UEFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel app_description;
    private javax.swing.JPanel app_options;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JLabel close_btn;
    private javax.swing.JTextField code;
    private javax.swing.JComboBox<String> filiere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField libelle;
    private javax.swing.JFormattedTextField nb_credit;
    private javax.swing.JFormattedTextField vol_cm;
    private javax.swing.JFormattedTextField vol_td;
    private javax.swing.JFormattedTextField vol_tp;
    // End of variables declaration//GEN-END:variables
}
